//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSP.DataAccess.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSP.DataAccess.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading a map from the path &apos;{0}&apos; with the message: {1}.
        /// </summary>
        internal static string ExLoadMapError {
            get {
                return ResourceManager.GetString("ExLoadMapError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The read file does not contain any information to read points. The path is &apos;{0}&apos;.
        /// </summary>
        internal static string ExLoadPointEmpty {
            get {
                return ResourceManager.GetString("ExLoadPointEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The read of the file with the path &apos;{0}&apos; faild. Message: {1}.
        /// </summary>
        internal static string ExLoadPointError {
            get {
                return ResourceManager.GetString("ExLoadPointError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPTextSaveLoad.LoadRows(path) was not able to read the data..
        /// </summary>
        internal static string ExLoadPointErrorUnknown {
            get {
                return ResourceManager.GetString("ExLoadPointErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The read point has a non numeric string at the {0} value. The index is &apos;{1}&apos;, it is located in the file &apos;{2}&apos; and has the text &apos;{3}&apos;.
        /// </summary>
        internal static string ExLoadPointNoNumber {
            get {
                return ResourceManager.GetString("ExLoadPointNoNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving a map to the path &apos;{0}&apos; with the message: {1}.
        /// </summary>
        internal static string ExSaveMapError {
            get {
                return ResourceManager.GetString("ExSaveMapError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving points to the path &apos;{0}&apos; with the message: {1}.
        /// </summary>
        internal static string ExSavePointError {
            get {
                return ResourceManager.GetString("ExSavePointError", resourceCulture);
            }
        }
    }
}
